version: 2
updates:
  # Kích hoạt kiểm tra phiên bản cho pip (Python)
  - package-ecosystem: "pip"
    directory: "/" # Nơi chứa file requirements.txt
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"

  # Vẫn giữ lại phần quét GitHub Actions (rất tốt)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci"
